# Rigid environment
[Scene]
sideViewSize=[750, 450]

[Simulation]
ROS=true
GUI=false

[EndoscopeWagons]
number=1
position=[[-600,-1000,0]]
instrumentsHead=["gripper","gripper"]
hysteresis=[1, 1, 1, 1]  # in mm, cables' play
# hysteresis: [up/down flexion endoscope,
#              left/right flexion endoscope,
#              flexion left instrument,
#              flexion right instrument]

[Items]
    [Items.Box]
    position=[[700,50,0]]
    filename='scripts/environment/mesh/box.stl'
    collisionFilename='scripts/environment/mesh/boxCollision.stl'
    withCollision=true
    color=[[0.6,0.6,0.6,1.0]]
    type='Rigid'

    [Items.Cylinder1]
    filename='scripts/environment/mesh/cylinder1.stl'
    position=[[800,-60,-100]]
    withCollision=true
    color=[[0.4,0.4,0.4,1.0]]
    type='Rigid'

    [Items.Cylinder2]
    filename='scripts/environment/mesh/cylinder2.stl'
    position=[[700,0,235]]
    withCollision=true
    color=[[0.4,0.4,0.4,1.0]]
    type='Rigid'

    [Items.Cylinder3]
    filename='scripts/environment/mesh/cylinder3.stl'
    position=[[700,0,-245]]
    withCollision=true
    color=[[0.4,0.4,0.4,1.0]]
    type='Rigid'

    [Items.TorusStatic]
    number=2
    filename='scripts/environment/mesh/torus.stl'
    collisionFilename='scripts/environment/mesh/torusCollision.stl'
    position=[[800,-90,-100],[800.0,-86.5,-100.0]]
    scale=[[1.0,0.75,1.0]]
    withSolver=false
    withCollision=[false,true]
    color=[[0.3,0.1,0.1,1.0]]
    type='Rigid'